# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/datasetsDynamic',
                'doc_host': 'https://kaiguender.github.io',
                'git_url': 'https://github.com/kaiguender/datasetsDynamic',
                'lib_path': 'datasetsDynamic'},
  'syms': { 'datasetsDynamic.core': {'datasetsDynamic.core.foo': ('core.html#foo', 'datasetsDynamic/core.py')},
            'datasetsDynamic.loadData': { 'datasetsDynamic.loadData.add_lag_features': ( 'loaddata.html#add_lag_features',
                                                                                         'datasetsDynamic/loadData.py'),
                                          'datasetsDynamic.loadData.loadDataYaz': ( 'loaddata.html#loaddatayaz',
                                                                                    'datasetsDynamic/loadData.py')}}}
